apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quiz-app
  name: quiz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-app
  template:
    metadata:
      labels:
        app: quiz-app
    spec:
      containers:
        - image: ghcr.io/amo-yotakenoko/quiz:6e423c8b75a37517f024e5429ae669aa4fb6f937
          name: quiz-app
