apiVersion: v1
kind: Service
metadata:
  labels:
    app: quiz-app
  name: quiz-app
spec:
  selector:
    app: quiz-app
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP

