apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quiz-app
  name: quiz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-app
  template:
    metadata:
      labels:
        app: quiz-app
    spec:
      containers:
        - image: ghcr.io/amo-yotakenoko/quiz:7d376882e047b8197259692ec996fe04810b43a4
          name: quiz-app
