apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quiz-app
  name: quiz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-app
  template:
    metadata:
      labels:
        app: quiz-app
    spec:
      containers:
        - image: ghcr.io/amo-yotakenoko/quiz:7ef946a154c2c5a85d66d565ed3ca75a0d450abf
          name: quiz-app
