apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quiz-app
  name: quiz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-app
  template:
    metadata:
      labels:
        app: quiz-app
    spec:
      containers:
        - image: ghcr.io/amo-yotakenoko/quiz:3c4fe08dc1cf92ef2d3897724d29a67ed4edf847
          name: quiz-app
