apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quiz-app
  name: quiz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-app
  template:
    metadata:
      labels:
        app: quiz-app
    spec:
      containers:
        - image: ghcr.io/amo-yotakenoko/quiz:c6f6903570ae96d255351d3409494a1b956692a1
          name: quiz-app
