"""quastiontest

Revision ID: 0354a4fc883c
Revises: c8194b0a0911
Create Date: 2024-07-01 13:42:25.444240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0354a4fc883c'
down_revision = 'c8194b0a0911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('mail', sa.VARCHAR(length=128), nullable=True),
    sa.Column('password', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail')
    )
    # ### end Alembic commands ###
