"""Initial migration

Revision ID: 874d7a53364e
Revises: 
Create Date: 2024-06-10 15:23:23.232519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874d7a53364e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GameLog',
    sa.Column('participatingiserid', sa.Integer(), nullable=True),
    sa.Column('gamenumber', sa.Integer(), nullable=True),
    sa.Column('questionsetlist', sa.String(length=128), nullable=True),
    sa.Column('questionasked', sa.Integer(), nullable=True),
    sa.Column('howtoanswer', sa.String(length=128), nullable=True),
    sa.Column('gamelogid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('gamelogid')
    )
    op.create_table('Question',
    sa.Column('questionsetid', sa.Integer(), nullable=True),
    sa.Column('questionid', sa.Integer(), nullable=False),
    sa.Column('questiontext', sa.String(length=128), nullable=True),
    sa.Column('answer', sa.String(length=128), nullable=True),
    sa.Column('questionformat', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('correctcount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('questionid')
    )
    op.create_table('Questionset',
    sa.Column('questionsetid', sa.Integer(), nullable=False),
    sa.Column('questionsetitle', sa.String(length=128), nullable=True),
    sa.Column('questionsetowner', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('questionsetid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Questionset')
    op.drop_table('Question')
    op.drop_table('GameLog')
    op.drop_table('Account')
    # ### end Alembic commands ###
