"""idをintegerからstringへ

Revision ID: 87ff1a394a34
Revises: 874d7a53364e
Create Date: 2024-06-10 15:52:11.238685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ff1a394a34'
down_revision = '874d7a53364e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Account', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Account', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=128),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
